name: build jdk
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-16.04, macos-10.15, windows-2016 ]
        javaToBuild: [ jdk11u ]
    steps:
      - name: Run build script
        run: ./bin/ci-build.sh
        shell: bash